# This is a basic workflow to help you get started with Actions

name: OneFLOW_Linux_MPI_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Linux OneFLOW MPI Run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MPICH2
        run: |
          echo cd ${{ github.workspace }}
          cd ${{ github.workspace }}
          echo ls
          ls
          echo sudo apt install mpich
          sudo apt install mpich
          echo ----------------------------------------
          echo mpirun --version
          mpirun --version
          echo ----------------------------------------
          echo which mpirun
          which mpirun
        shell: bash
      - name: CMake Build
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir build
          cd build
          cmake --version
          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} ../
          ls
        shell: bash
      - name: CMake Install
        env:
          prefix: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/build
          ls
          make -j 4
          make install
          ls "${{env.prefix}}"
          cd "${{env.prefix}}/bin"
        shell: bash